#!/bin/bash
# set -x
[ $# -lt 3 ] && { echo "Usage: $0 destination, BaseUrl or site name not given"; exit 1; }
# Script to generate Hebrew site, rename index.xml files and their references to hindex.xml,
# rename top index.html to hindex.html then merge all into the English site.
# Result is to have both English and Hebrew cooexisting in the same branch
#

targ=$1
l1targ=/tmp/${l1}/$3/public
l2targ=/tmp/${l2}/$3/public
l1content=${l1}content
l2content=${l2}content
l1index=${l1}index
lindex=${l2}index
l1config=config${l1}.toml
l2config=config${l2}.toml

[[ ! -d ${l1content} ]] && { echo "${l1content} directory missing"; exit 1; }
[[ ! -d ${l2content} ]] && { echo "${l2content} directory missing"; exit 1; }
# Hebrew (first language) section
hugo --config="${l1config}" -d ${l1targ} -t $HUGO_THEME -b $2 # Make Hebrew site in hpublic
# echo "333 $3"
# Change the string "index.xml" appearing in all the files named index.* to "hindex.xml"
dir=${l1targ}
find $dir -type f -name 'index.*' -exec sed -i "s/index.xml/${l1index}.xml/" {} +
# Rename all the files named index.xml hindex.html
for file in $(find $dir -type f -name index.xml); do
    mv $file $(dirname "${file}")/${l1index}.xml
done
mv $dir/{,${l1}}index.html # Rename top level index.html to hindex.html
# echo "444 $3"
hugo --config="${l2config}" -d ${l2targ} -t $HUGO_THEME -b $2 # Make English site in epublic
# echo "555 $3"
# Make eindex copies of top level index.html and index.html
cp ${l2targ}/{,${l2}}index.html && cp ${l2targ}/{,${l2}}index.xml
# Merge hpublic and epublic into target
# First English
# echo "666 $3"
rsync -a ${l2targ}/ $targ
# echo "777 $3"

# Then Hebrew (Don't need static/ twice)
# echo "888 $3"
rsync -a --exclude={/images/,/css/,/js/,/data/,/docs/,/slides/} ${l1targ}/ $targ
# echo "999 $3"
