#!/bin/bash
# set -x
[ $# -lt 3 ] && { echo "Usage: $0 destination, BaseUrl or site name not given"; exit 1; }
# Script to generate Hebrew site, rename index.xml files and their references to hindex.xml,
# rename top index.html to hindex.html then merge all into the English site.
# Result is to have both English and Hebrew cooexisting in the same serving branch

dest=$1
baseurl=$2
lang1dest=/tmp/${lang1}/$3/public
lang1content=${lang1}content
lang1index=${lang1}index
lang1config=config${lang1}.toml
echo "We\'re in fkms\n"
[[ ! -d ${lang1content} ]] && { echo "${lang1content} directory missing"; exit 1; }
# Hebrew (first language) section
hugo --config="${lang1config}" -d ${lang1dest} -t $HUGO_THEME -b $baseurl # Make Hebrew site in hpublic

# Change the string "index.xml" appearing in all the files named index.* to "hindex.xml"
find $lang1dest -name js -name css -name docs -name images -name slides -prune -o -type f -name 'index.*' -exec sed -i "s/index.xml/${lang1index}.xml/" {} +
# Rename all the files named index.xml hindex.html
for file in $(find $lang1dest -name js -name css -name docs -name slides -prune -o -type f -name index.xml); do
    mv $file $(dirname "${file}")/${lang1index}.xml
done
mv $lang1dest/{,${lang1}}index.html # Rename top level index.html to hindex.html
hugo -d $dest -t $HUGO_THEME -b $baseurl # Make default (English) site in public
# Merge 1st non-default language into default (English) destination
rsync -a --exclude={/images/,/css/,/js/,/data/,/docs/,/slides/} ${lang1dest}/ $dest
