#!/bin/bash
#
# Use with Caddy startup command to clone levpoem or heartbt etc. and run Hugo
# set -x
#
[ $# -eq 0 ] && { echo "Usage: $0 destination not given"; exit 1; }
[ ! -d /var/www/src/$1 ] && { echo "no source dir"; exit 1; }
cd /var/www/src/$1
# If given, the second parameter is the BaseUrl. If not, BaseUrl is built by default from the 1st parameter
# echo "\$@ is " $@
runhugo $@
